version: '3.8'

services:
  mysql:
    image: mariadb:10.4
    container_name: mariadb-local
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "graduates"
    ports:
      - "3306:3306"
    volumes:
      - ./support/env/dev/scripts:/docker-entrypoint-initdb.d:ro

volumes:
  mysql-data:
